apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-alert-svc
spec:
  type: {{ .Values.alertsvc.service.type }}  # LoadBalancer, ClusterIP, or NodePort
  ports:
    - port: 5003
      targetPort: 5003
  selector:
    app: {{ .Release.Name }}-alert-svc
