apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  type: {{ .Values.backend.service.type }}  # LoadBalancer, NodePort, or ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: {{ .Release.Name }}-backend
