image: mcr.microsoft.com/powershell

variables:
  IMAGE_IMAGE: docker.io/abhishekcha/stock-project-microservice

stages:
  - build-push
  - deploy

# Job to push all images to GitLab registry
push_images:
  stage: build-push
  script:
    - docker login -u "abhishekcha" -p "$DOCKERHUB_TOKEN"
    - pwsh /push.ps1
  only:
    - main
