image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_IMAGE: abhishekcha/stock-project-microservice
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2376
  DOCKER_DRIVER: overlay2

stages:
  - deploy

deploy:
   tags:
     - amazon-linux
   stage: deploy
   script:
     - docker run hello-world