image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_IMAGE: docker.io/abhishekcha/stock-project-microservice

stages:
  - buid-push
  - deploy

# Job to push all images to GitLab registry
push_images:
  stage: push
  script:
    - docker login -u "abhishekcha" -p "$DOCKERHUB_TOKEN"
    - pwsh /push.ps1
  only:
    - main
