image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_IMAGE: abhishekcha/stock-project-microservice
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2376
  DOCKER_DRIVER: overlay2

stages:
  - deploy

deploy:
   tags:
     - amazon-linux
   stage: deploy
   before_script:
    - sudo usermod -aG docker gitlab-runner
    - sudo service docker start
   script:
     - docker-compose up --build