image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_IMAGE: abhishekcha/stock-project-microservice
  # Add these important Docker TLS variables
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2376
  DOCKER_DRIVER: overlay2

stages:
  - deploy

deploy:
   tags:
     - amazon-linux
   stage: deploy
   script:
     - apk add --no-cache docker-compose
     - docker-compose up --build