#version: '3'
services:
  frontend:
    build: ./frontend
    image: abhishekcha/stock-project-microservice:frontend  # Add image here
    ports:
      - "80:80"
    environment:
      - API_URL=http://localhost:5000
      - STOCKS_URL=http://localhost:5002/stocks
      - UPLOAD_URL=http://localhost:5001/upload
      - SALERT_URL=http://localhost:5003/set-alert
      - IMGMT_URL=http://localhost:5004
    depends_on:
      - backend

  backend:
    build: ./backend
    image: abhishekcha/stock-project-microservice:backend  # Add image here
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ****
      DB_USER: ****
      DB_PASSWORD: ****
      DB_DATABASE: ****

  upload:
    build:
      context: ./upload
    image: abhishekcha/stock-project-microservice:upload  # Add image here
    ports:
      - "5001:5001"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/bubbly-mantis.json
    volumes:
      - ./upload:/app
    command: >
      sh -c "service nginx start && python3 upload.py"

  sharemarket:
    build:
      context: ./sharemarket
    image: abhishekcha/stock-project-microservice:sharemarket  # Add image here
    ports:
      - "5002:5002"
    volumes:
      - ./sharemarket:/app
    command: >
      sh -c "service nginx start && python3 app.py"

  alert-svc:
    build: ./alert-svc
    image: abhishekcha/stock-project-microservice:alert-svc  # Add image here
    ports:
      - "5003:5003"

  inventory-mgmt:
    build: ./inventory-mgmt
    image: abhishekcha/stock-project-microservice:inventory-mgmt  # Add image here
    ports:
      - "5004:5004"
    environment:
      DB_HOST: ****
      DB_USER: ****
      DB_PASSWORD: ****
      DB_NAME: ****

volumes:
  mysql_data:
