# apiVersion: v1
# kind: Namespace
# metadata:
#   name: backend
#   namespace: backend
#   labels:
#     name: backend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
#  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: abhishekcha/stock-project-microservice:backend 
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "250m" 
            memory: "128Mi"
          limits:
            cpu: "500m"  
            memory: "256Mi"
        env:
        - name: DB_HOST
          value: "****"
        - name: DB_USER
          value: "****"
        - name: DB_PASSWORD
          value: "****"
        - name: DB_DATABASE
          value: "****"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
#  namespace: backend
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend
