apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: abhishekcha/stock-project-microservice:backend 
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "34.42.224.12"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "Qwerty@123"
        - name: DB_DATABASE
          value: "my_database"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend
