# apiVersion: v1
# kind: Namespace
# metadata:
#   name: inventory-mgmt
#   labels:
#     name: inventory-mgmt

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-mgmt
#  namespace: inventory-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-mgmt
  template:
    metadata:
      labels:
        app: inventory-mgmt
    spec:
      containers:
      - name: inventory-mgmt
        image: abhishekcha/stock-project-microservice:inventory-mgmt
        ports:
        - containerPort: 5004
        resources:
          requests:
            cpu: "250m"   # 250 millicores (0.25 CPU)
            memory: "128Mi" # 128 MiB
          limits:
            cpu: "500m"   # 500 millicores (0.5 CPU)
            memory: "256Mi" # 256 MiB
        env:
        - name: DB_HOST
          value: "****"
        - name: DB_USER
          value: "****"
        - name: DB_PASSWORD
          value: "****"
        - name: DB_NAME
          value: "****"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-mgmt
#  namespace: inventory-mgmt
spec:
  type: LoadBalancer
  ports:
  - port: 5004
    targetPort: 5004
  selector:
    app: inventory-mgmt
