# apiVersion: v1
# kind: Namespace
# metadata:
#   name: upload
#   namespace: upload
#   labels:
#     name: upload

apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
#  namespace: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload
        image: abhishekcha/stock-project-microservice:upload
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "250m"   # 250 millicores (0.25 CPU)
            memory: "128Mi" # 128 MiB
          limits:
            cpu: "500m"   # 500 millicores (0.5 CPU)
            memory: "256Mi" # 256 MiB

---
apiVersion: v1
kind: Service
metadata:
  name: upload
#  namespace: upload
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: alert-svc
