apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-svc
  template:
    metadata:
      labels:
        app: alert-svc
    spec:
      containers:
      - name: alert-svc
        image: abhishekcha/stock-project-microservice:alert-svc
        ports:
        - containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name: alert-svc
spec:
  ports:
  - port: 5003
    targetPort: 5003
  selector:
    app: alert-svc
