apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
#  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: abhishekcha/stock-project-microservice:frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"   # 250 millicores (0.25 CPU)
            memory: "128Mi" # 128 MiB
          limits:
            cpu: "500m"   # 500 millicores (0.5 CPU)
            memory: "256Mi" # 256 MiB
        env:
        # - name: API_URL
        #   value: "backend.backend.svc.cluster.local:5000"
        # - name: STOCKS_URL
        #   value: "sharemarket.sharemarket.svc.cluster.local:5002/stocks"
        # - name: UPLOAD_URL
        #   value: "upload.upload.svc.cluster.local:5001/upload"
        # - name: SALERT_URL
        #   value: alert-svc.alert-svc.svc.cluster.local:5003/set-alert
        # - name: IMGMT_URL
        #   value: "inventory-mgmt.inventory-mgmt.svc.cluster.local:5004"
        - name: API_URL
          value: 34.57.166.81:5000
        - name: STOCKS_URL
          value: 35.232.145.168:5002/stocks
        - name: UPLOAD_URL
          value: 34.173.21.63:5001/upload
        - name: SALERT_URL
          value: 35.184.133.17:5003/set-alert
        - name: IMGMT_URL
          value: 34.122.169.253:5004

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
#  namespace: frontend
spec:
  type: LoadBalancer # Change to ClusterIP or NodePort as needed
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
