# Configuration values for sharemarket deployment
sharemarket:
  replicas: 1  # Number of replicas for the deployment

  # Image configuration for the sharemarket container
  image:
    repository: abhishekcha/stock-project-microservice  # Docker image repository
    tag: sharemarket  # Docker image tag

  # Service configuration
  service:
    type: LoadBalancer  # Can be LoadBalancer, ClusterIP, or NodePort
    port: 5002  # External port for the service
    targetPort: 5002  # Container port to forward traffic to

  # Persistent volume claim settings
  pvc:
    storage: 1Gi  # Requesting 1Gi of storage for the PVC

  # Ingress configuration
ingress:
  enabled: false  # Set to true if you need ingress to be enabled
