backend:
  replicas: 1
  image:
    repository: abhishekcha/stock-project-microservice
    tag: backend  # You can change this to specify a versioned tag if needed

  db:
    host: "****"
    user: "****"
    password: "****"
    database: "****"

  service:
    type: LoadBalancer  # Can also be ClusterIP or NodePort

ingress:
  enabled: false
