

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc
#  namespace: alert-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-svc
  template:
    metadata:
      labels:
        app: alert-svc
    spec:
      containers:
      - name: alert-svc
        image: abhishekcha/stock-project-microservice:alert-svc
        ports:
        - containerPort: 5003
        resources:
          requests:
            cpu: "250m"   # 250 millicores (0.25 CPU)
            memory: "128Mi" # 128 MiB
          limits:
            cpu: "500m"   # 500 millicores (0.5 CPU)
            memory: "256Mi" # 256 MiB

---
apiVersion: v1
kind: Service
metadata:
  name: alert-svc
#  namespace: alert-svc
spec:
  type: LoadBalancer
  ports:
  - port: 5003
    targetPort: 5003
  selector:
    app: alert-svc
