apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharemarket-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sharemarket.pvc.storage }}  # Reference the PVC storage size from values.yaml
